module.exports = [
    {
        item: 'poop',
        price: 500,
        emoji: '💩',
        type: 'Item',
        description: 'Its shit what do you expect',
        onShop: true,
    },
    {
        item: 'subaru',
        description: 'The best car, except its not',
        price: 50000,
        type: 'Special item',
        emoji: '🚗',
        onShop: true,
    },
    {
        item: 'police car',
        description: 'Yes you can own one',
        price: 100000,
        type: 'Special item',
        emoji: '🚓',
        onShop: true,
    },
    {
        item: 'grapes',
        description: 'You may eat me!',
        type: 'Item',
        price: 1000,
        emoji: '🍇',
        onShop: true,
    },
    {
        item: 'banknote',
        description: 'Increase your banks campacity',
        type: 'Power Up',
        price: 100000,
        emoji: '💶',
        onShop: true,
    },
    {
        item: 'clock',
        description: 'Makes all the cooldowns for you take half as much time, for a lifetime!',
        type: 'Power Up',
        price: 1000000,
        emoji: '⏰',
        onShop: true,
    },
    {
        item: 'loot box',
        description: 'A box that you can get by voting !',
        type: 'Item',
        price: 100000,
        emoji: '📦',
        onShop: true,
    }
]